[project]
name = "pw-gen-cli"
version = "0.1.0"
description = "Generate a strong password with good randomness"
readme = "README.md"
authors = [
  {name = "Kisara Fernando", email = "kisarawenu@gmail.com"}
]
requires-python = ">=3.8"
dependencies = [
    "click>=8.1.8",
    "ruff>=0.16.2",
]

[project.scripts]
pwdgen = "pw_gen_cli.password_gen:pw_gen"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"

[dependency-groups]
dev = [
    "pytest>=8.3.5",
]

[tool.ruff]
lint.ignore = [
    "I001",
    "EXE002"
]
